# TCL File Generated by Component Editor 21.1
# Tue Nov 21 22:07:58 MSK 2023
# DO NOT MODIFY


# 
# controller "controller" v1.0
#  2023.11.21.22:07:58
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module controller
# 
set_module_property DESCRIPTION ""
set_module_property NAME controller
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME controller
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL controller
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file controller.v VERILOG PATH components/controller.v TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter I2C_DATA_LEN_MAX INTEGER 8
set_parameter_property I2C_DATA_LEN_MAX DEFAULT_VALUE 8
set_parameter_property I2C_DATA_LEN_MAX DISPLAY_NAME I2C_DATA_LEN_MAX
set_parameter_property I2C_DATA_LEN_MAX TYPE INTEGER
set_parameter_property I2C_DATA_LEN_MAX UNITS None
set_parameter_property I2C_DATA_LEN_MAX ALLOWED_RANGES -2147483648:2147483647
set_parameter_property I2C_DATA_LEN_MAX HDL_PARAMETER true
add_parameter I2C_DATA_WIDTH INTEGER 8
set_parameter_property I2C_DATA_WIDTH DEFAULT_VALUE 8
set_parameter_property I2C_DATA_WIDTH DISPLAY_NAME I2C_DATA_WIDTH
set_parameter_property I2C_DATA_WIDTH TYPE INTEGER
set_parameter_property I2C_DATA_WIDTH UNITS None
set_parameter_property I2C_DATA_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property I2C_DATA_WIDTH HDL_PARAMETER true
add_parameter I2C_ADDR_WIDTH INTEGER 7
set_parameter_property I2C_ADDR_WIDTH DEFAULT_VALUE 7
set_parameter_property I2C_ADDR_WIDTH DISPLAY_NAME I2C_ADDR_WIDTH
set_parameter_property I2C_ADDR_WIDTH TYPE INTEGER
set_parameter_property I2C_ADDR_WIDTH UNITS None
set_parameter_property I2C_ADDR_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property I2C_ADDR_WIDTH HDL_PARAMETER true
add_parameter I2C_WR_BIT STD_LOGIC_VECTOR 0
set_parameter_property I2C_WR_BIT DEFAULT_VALUE 0
set_parameter_property I2C_WR_BIT DISPLAY_NAME I2C_WR_BIT
set_parameter_property I2C_WR_BIT TYPE STD_LOGIC_VECTOR
set_parameter_property I2C_WR_BIT UNITS None
set_parameter_property I2C_WR_BIT ALLOWED_RANGES 0:3
set_parameter_property I2C_WR_BIT HDL_PARAMETER true
add_parameter I2C_RD_BIT STD_LOGIC_VECTOR 1
set_parameter_property I2C_RD_BIT DEFAULT_VALUE 1
set_parameter_property I2C_RD_BIT DISPLAY_NAME I2C_RD_BIT
set_parameter_property I2C_RD_BIT TYPE STD_LOGIC_VECTOR
set_parameter_property I2C_RD_BIT UNITS None
set_parameter_property I2C_RD_BIT ALLOWED_RANGES 0:3
set_parameter_property I2C_RD_BIT HDL_PARAMETER true
add_parameter CLK_FREQ_HZ INTEGER 50
set_parameter_property CLK_FREQ_HZ DEFAULT_VALUE 50
set_parameter_property CLK_FREQ_HZ DISPLAY_NAME CLK_FREQ_HZ
set_parameter_property CLK_FREQ_HZ TYPE INTEGER
set_parameter_property CLK_FREQ_HZ UNITS None
set_parameter_property CLK_FREQ_HZ ALLOWED_RANGES -2147483648:2147483647
set_parameter_property CLK_FREQ_HZ HDL_PARAMETER true
add_parameter UART_BAUDRATE INTEGER 9600
set_parameter_property UART_BAUDRATE DEFAULT_VALUE 9600
set_parameter_property UART_BAUDRATE DISPLAY_NAME UART_BAUDRATE
set_parameter_property UART_BAUDRATE TYPE INTEGER
set_parameter_property UART_BAUDRATE UNITS None
set_parameter_property UART_BAUDRATE ALLOWED_RANGES -2147483648:2147483647
set_parameter_property UART_BAUDRATE HDL_PARAMETER true
add_parameter CLK_I2C_HZ INTEGER 100
set_parameter_property CLK_I2C_HZ DEFAULT_VALUE 100
set_parameter_property CLK_I2C_HZ DISPLAY_NAME CLK_I2C_HZ
set_parameter_property CLK_I2C_HZ TYPE INTEGER
set_parameter_property CLK_I2C_HZ UNITS None
set_parameter_property CLK_I2C_HZ ALLOWED_RANGES -2147483648:2147483647
set_parameter_property CLK_I2C_HZ HDL_PARAMETER true
add_parameter wait_500ms INTEGER 25000000
set_parameter_property wait_500ms DEFAULT_VALUE 25000000
set_parameter_property wait_500ms DISPLAY_NAME wait_500ms
set_parameter_property wait_500ms TYPE INTEGER
set_parameter_property wait_500ms UNITS None
set_parameter_property wait_500ms ALLOWED_RANGES -2147483648:2147483647
set_parameter_property wait_500ms HDL_PARAMETER true
add_parameter I2C_SLAVE_ADDR STD_LOGIC_VECTOR 72
set_parameter_property I2C_SLAVE_ADDR DEFAULT_VALUE 72
set_parameter_property I2C_SLAVE_ADDR DISPLAY_NAME I2C_SLAVE_ADDR
set_parameter_property I2C_SLAVE_ADDR TYPE STD_LOGIC_VECTOR
set_parameter_property I2C_SLAVE_ADDR UNITS None
set_parameter_property I2C_SLAVE_ADDR ALLOWED_RANGES 0:255
set_parameter_property I2C_SLAVE_ADDR HDL_PARAMETER true
add_parameter TEMPER_REG_ADDR STD_LOGIC_VECTOR 0
set_parameter_property TEMPER_REG_ADDR DEFAULT_VALUE 0
set_parameter_property TEMPER_REG_ADDR DISPLAY_NAME TEMPER_REG_ADDR
set_parameter_property TEMPER_REG_ADDR TYPE STD_LOGIC_VECTOR
set_parameter_property TEMPER_REG_ADDR UNITS None
set_parameter_property TEMPER_REG_ADDR ALLOWED_RANGES 0:511
set_parameter_property TEMPER_REG_ADDR HDL_PARAMETER true
add_parameter FSM_State_IDLE INTEGER 0
set_parameter_property FSM_State_IDLE DEFAULT_VALUE 0
set_parameter_property FSM_State_IDLE DISPLAY_NAME FSM_State_IDLE
set_parameter_property FSM_State_IDLE TYPE INTEGER
set_parameter_property FSM_State_IDLE UNITS None
set_parameter_property FSM_State_IDLE ALLOWED_RANGES -2147483648:2147483647
set_parameter_property FSM_State_IDLE HDL_PARAMETER true
add_parameter FSM_State_READ_TEMPER INTEGER 1
set_parameter_property FSM_State_READ_TEMPER DEFAULT_VALUE 1
set_parameter_property FSM_State_READ_TEMPER DISPLAY_NAME FSM_State_READ_TEMPER
set_parameter_property FSM_State_READ_TEMPER TYPE INTEGER
set_parameter_property FSM_State_READ_TEMPER UNITS None
set_parameter_property FSM_State_READ_TEMPER ALLOWED_RANGES -2147483648:2147483647
set_parameter_property FSM_State_READ_TEMPER HDL_PARAMETER true
add_parameter FSM_State_SEND_TEMPER INTEGER 3
set_parameter_property FSM_State_SEND_TEMPER DEFAULT_VALUE 3
set_parameter_property FSM_State_SEND_TEMPER DISPLAY_NAME FSM_State_SEND_TEMPER
set_parameter_property FSM_State_SEND_TEMPER TYPE INTEGER
set_parameter_property FSM_State_SEND_TEMPER UNITS None
set_parameter_property FSM_State_SEND_TEMPER ALLOWED_RANGES -2147483648:2147483647
set_parameter_property FSM_State_SEND_TEMPER HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset_n
# 
add_interface reset_n reset end
set_interface_property reset_n associatedClock clock
set_interface_property reset_n synchronousEdges DEASSERT
set_interface_property reset_n ENABLED true
set_interface_property reset_n EXPORT_OF ""
set_interface_property reset_n PORT_NAME_MAP ""
set_interface_property reset_n CMSIS_SVD_VARIABLES ""
set_interface_property reset_n SVD_ADDRESS_GROUP ""

add_interface_port reset_n en reset_n Input 1


# 
# connection point uart
# 
add_interface uart conduit end
set_interface_property uart associatedClock clock
set_interface_property uart associatedReset reset_n
set_interface_property uart ENABLED true
set_interface_property uart EXPORT_OF ""
set_interface_property uart PORT_NAME_MAP ""
set_interface_property uart CMSIS_SVD_VARIABLES ""
set_interface_property uart SVD_ADDRESS_GROUP ""

add_interface_port uart uart_rx_busy rx_busy Input 1
add_interface_port uart uart_rx_data rx_data Input 16
add_interface_port uart uart_rx_ready rx_ready Input 1
add_interface_port uart uart_tx_data tx_data Output 16
add_interface_port uart uart_tx_dv tx_dv Output 1
add_interface_port uart uart_tx_ready tx_ready Input 1


# 
# connection point i2c
# 
add_interface i2c conduit end
set_interface_property i2c associatedClock clock
set_interface_property i2c associatedReset reset_n
set_interface_property i2c ENABLED true
set_interface_property i2c EXPORT_OF ""
set_interface_property i2c PORT_NAME_MAP ""
set_interface_property i2c CMSIS_SVD_VARIABLES ""
set_interface_property i2c SVD_ADDRESS_GROUP ""

add_interface_port i2c i2c_ack_error ack_error Bidir 1
add_interface_port i2c i2c_addr addr Output 7
add_interface_port i2c i2c_busy busy Input 1
add_interface_port i2c i2c_data_rd data_rd Input 8
add_interface_port i2c i2c_data_wr data_wr Output 8
add_interface_port i2c i2c_ena ena Output 1
add_interface_port i2c i2c_rw rw Output 1


# 
# connection point leds
# 
add_interface leds conduit end
set_interface_property leds associatedClock clock
set_interface_property leds associatedReset reset_n
set_interface_property leds ENABLED true
set_interface_property leds EXPORT_OF ""
set_interface_property leds PORT_NAME_MAP ""
set_interface_property leds CMSIS_SVD_VARIABLES ""
set_interface_property leds SVD_ADDRESS_GROUP ""

add_interface_port leds leds leds Output 4


# 
# connection point data_7seg
# 
add_interface data_7seg conduit end
set_interface_property data_7seg associatedClock clock
set_interface_property data_7seg associatedReset reset_n
set_interface_property data_7seg ENABLED true
set_interface_property data_7seg EXPORT_OF ""
set_interface_property data_7seg PORT_NAME_MAP ""
set_interface_property data_7seg CMSIS_SVD_VARIABLES ""
set_interface_property data_7seg SVD_ADDRESS_GROUP ""

add_interface_port data_7seg data_7seg data_7seg Output 8


# 
# connection point keys
# 
add_interface keys conduit end
set_interface_property keys associatedClock clock
set_interface_property keys associatedReset reset_n
set_interface_property keys ENABLED true
set_interface_property keys EXPORT_OF ""
set_interface_property keys PORT_NAME_MAP ""
set_interface_property keys CMSIS_SVD_VARIABLES ""
set_interface_property keys SVD_ADDRESS_GROUP ""

add_interface_port keys key_read key_read Input 1

